version: "3.9"

services:
  backend:
    build: ./sae_back
    container_name: backend_sae
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sae518?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build: ./sae_front
    container_name: frontend_sae
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_sae
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sae518
    ports:
      - "3306:3306"
